### ISSUE TITLE
Response payload encoded 2X

### ISSUE THREAD

**Issue by duskoo** [Co-Epi/coepi-backend-aws#18]
Response payload has to be decoded twice to get to the "plaintext".

**Current**
```
 curl -v \
	-X POST \
	-H "Accept-Language: en;q=1.0" \
	-H "Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8" \
	-H "User-Agent: Unknown/Unknown (com.apple.dt.xctest.tool; build:15702; iOS 13.3.0) Alamofire/5.0.5" \
	-d "VGVzdCBwYXlsb2FkIDE1ODczOTg1NzcuNDc3NjA5Mg==" \
	"https://18ye1iivg6.execute-api.us-west-1.amazonaws.com/v4/tcnreport"
```

When fetching I get something like:
`    "VkdWemRDQndZWGxzYjJGa0lERTFPRGN6T1RnMU56Y3VORGMzTmpBNU1nPT0="`

after decoding twice, the returned string becomes:

`Test payload 1587398577.4776092`

**Expected**
Returned payload yields "Test payload ..." after single Base64 decoding operation.

**Comment by bhushanRamnani** [comment]
Fixed with https://github.com/Co-Epi/coepi-backend-aws/pull/19
