### ISSUE TITLE
[coepi-backend-aws][v4]: Do report signature validation on the server side before persisting the data

### ISSUE THREAD

**Issue by bhushanRamnani** [Co-Epi/coepi-backend-aws#9]
Currently, the v4 API endpoint receives the report data as a POST request, stores the report data buffer as is and serves it in a GET request. It does not perform any report validation and signature verification as per the TCN protocol. There is a Kotlin library that can be used to achieve that. Report validation and signature verification need to be added here -> https://github.com/Co-Epi/coepi-backend-aws/blob/master/src/main/kotlin/org/coepi/api/v4/TCNCloudAPIHandler.kt#L141-L142

This requires knowledge of the TCN protocol:
https://github.com/TCNCoalition/TCN/blob/main/README.md

There is already a Kotlin library that can be re-used:
https://github.com/TCNCoalition/tcn-client-android/tree/develop/tcn-client-android/src/main/java/org/tcncoalition/tcnclient/crypto

**Comment by bhushanRamnani** [comment]
https://github.com/TCNCoalition/TCN/blob/main/src/serialize.rs

https://github.com/TCNCoalition/TCN/blob/main/README.md

**Comment by bhushanRamnani** [comment]
This library can probably be shared with the android app. Make sure to check if it's already been developed.

**Comment by ramnanib2** [comment]
Completed with https://github.com/Co-Epi/coepi-backend-aws/commit/4fb51b67c5a1155c5de1a87caa75874951223a6b
